spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG